### ISSUE TITLE
markdown kerning on Linux/Ubuntu

### ISSUE THREAD

**Issue by bonesmoses** [d2lang/d2#1103]
When using a non-sketch render mode, markdown text blocks may fail to render some contents. The following example illustrates:

```yaml
direction: right

explanation: |md
  # Notes:
  * This will show up fine.  
  * This will be clipped.
| {
  near: top-center
}

node_design: Box o Stuff {
  style.border-radius: 10

  a <-> b <-> c
}
```

First, how it looks in sketch mode:

![non-clipped](https://user-images.githubusercontent.com/719860/228671230-c6d6420c-9113-48bf-816c-1be8a4c50cb7.png)

Then when using standard rendering:

![clipped](https://user-images.githubusercontent.com/719860/228671364-5596f0e4-632d-43f9-afda-b181d7d0800f.png)

Perhaps an additional note is that the rendered text area also appears to be smaller in general, as the first line wraps in standard render mode, but not in sketch.

The playground also does not exhibit either of these effects.
